enum ProductionLineActivityType{
  START_PRODUCTION_LINE,
  STOP_PRODUCTION_LINE,
  START_WORK_ORDER,
  START_PRODUCE,
  PAUSE,
  RESUME_PRODUCE,
  STOP_WORK_ORDER,
  USER_CHECK_IN,
  USER_CHECK_OUT
}