enum ReportType{
  ORDER_PICK_SHEET,
  RECEIVING_DOCUMENT,
  PUTAWAY_DOCUMENT,
  PICK_LIST_SHEET,
  DELIVERY_NOTE,
  PACKING_SLIP,
  CYCLE_COUNT_SHEET,
  AUDIT_COUNT_SHEET,
  LPN_REPORT,
  WORK_ORDER_PICK_SHEET,
  PRODUCTION_LINE_ASSIGNMENT_REPORT,
  BILL_OF_LADING,
  LPN_LABEL,
  PRODUCTION_LINE_ASSIGNMENT_LABEL,
  RECEIVING_LPN_LABEL,
  QC_INSPECTION_REQUEST_REPORT,
  RECEIVING_LPN_REPORT,
  PARCEL_LABEL,
  PARCEL_REPORT,
}

ReportType reportTypeFromString(String value){
  return ReportType.values.firstWhere((e)=>
  e.toString().split('.')[1].toUpperCase()==value.toUpperCase());
}